services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Karachi
    volumes:
      - /home/media-backup/docker/emby/library:/config
      - /home/media-backup/Anime:/data/tvshows
#     - /path/to/movies:/data/movies
#     - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8097:8096
      - 8921:8920 #optional
    restart: unless-stopped
