services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Karachi
    # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /home/media-backup/docker/jellyfin/library:/config
      - /home/media-backup/Anime:/data/tvshows
    # - /path/to/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
~                                                                                                                                                                                                                   
~                                     
